### ISSUE TITLE
Error when upgrading gemoji - SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by montoya332** [wooorm/gemoji#13]
Getting this error when upgrading package and running jest  unit tests 
```
/**/node_modules/gemoji/index.js:20
export const gemoji = [
    ^^^^^^
    SyntaxError: Unexpected token 'export'
    > 1 | import gemoji from "gemoji";
        | ^
```
Any suggestions on alternatives

**Comment by wooorm** [comment]
Hey, `export` is modern JavaScript.
`jest` is essentially unmaintained.
More info here https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c.

tldr: switch to ESM or use an older version of this package.
