### ISSUE TITLE
please add unicode version for each emoji

### ISSUE THREAD

**Issue by KraXen72** [wooorm/gemoji#14]
for example, if i know that the target os is windows 10, which had it's last emoji update of emoji 12.0 in 2019, i could filter out all newer emoji.
this would be very useful.

**Comment by wooorm** [comment]
> this would be very useful.

Why would it be useful?

Someone could use a different font, that does support them?

When someone sends the character over the internet to someone else, they would be able to display it?

Why not use an older version of this package?

**Comment by KraXen72** [comment]
i want to use this in an obsidian plugin, so i would check for the os and then filter out unsupported emoji. (using an older version is not an option, some systems might support it).
if there is a reliable mechanism to filter out emojis that cannot be displayed in js, please let me know. your point about a custom font is valid, i'd rather check against the font directly. i'll do some further research

**Comment by KraXen72** [comment]
i found [this](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/emoji.js) - looks kind of hacky, but should work. if you have a better idea, let me know, otherwise, feel free to close this issue.
edit: i could also possibly add an emoji-only font to fill in the missing native emojis

**Comment by wooorm** [comment]
> obsidian plugin

Doesn’t obsidian run in a browser?
The OS is not what you are looking for. The version when it was added to unicode is not what you are looking for.
People might support it. Or not. Relating to fonts and time in space. Not OS/Unicode.

> i found [this](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/emoji.js) - looks kind of hacky,

Right. You can detect if something is rendered, *currently*.
But emoji are bytes sent over the internet. Just like an `a` or whatever else.
There is nothing guaranteeing that viewers on the other side of the wire can or cannot see them.

> i could also possibly add an emoji-only font to fill in the missing native emojis

Yes, you could.

---

Closing is wontfix for this use case!
