### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by Omkaragrawal** [wooorm/gemoji#9]
[This package](https://www.jsdelivr.com/package/npm/gemoji) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`.

It would be good to get it via jsdelivr

**Comment by wooorm** [comment]
A PR is welcome for to add a `main: 'index.json'`, thanks!
